apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.10.1
  name: config-sugar
  namespace: knative-eventing
data:
  trigger-selector: "{}"
  