apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: slack-events
  namespace: slack
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    namespace: slack
    selector:
      matchLabels:
        function.knative.dev/name: slack-events
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
      namespace: eventing
