apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeui
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeui-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeui
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeui-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: kubeui
type: kubernetes.io/service-account-token
