apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: slack-send-message
  namespace: eventing
spec:
  broker: default
  filter:
    attributes:
      type: hypsibius.slack.send_message
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: slack-send-message
      namespace: slack
