apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: slack-conversation-select
  namespace: eventing
spec:
  broker: default
  filter:
    attributes:
      type: slack.blockAction.multi_static_select
      actionid: conversations.select
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: slack-channel-management
      namespace: mongodb
