apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: slack-member-joined-channel
  namespace: eventing
spec:
  broker: default
  filter:
    attributes:
      type: slack.event.member_joined_channel
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: slack-channel-management
      namespace: mongodb
