apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tracing
  namespace: knative-eventing
data:
  backend: "zipkin"
  zipkin-endpoint: "http://otel-collector.observability.svc.cluster.local:9411/api/v2/spans"
  debug: "true"
