apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
---
kind: Service
apiVersion: v1
metadata:
  name: jaeger-query-external-svc
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - protocol: TCP
      nodePort: 30686
      port: 16686
      targetPort: 16686
