apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: rabbit-broker-config
  namespace: slack
spec:
  rabbitmqClusterReference:
    name: rabbit-cluster
    namespace: rabbit
  queueType: quorum
