apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: parallel
  namespace: eventing
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Parallel
      name: distribute-to-brokers
