apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: distribute-to-brokers
  namespace: eventing
spec:
  branches:
    - subscriber:
        ref:
          apiVersion: eventing.knative.dev/v1
          kind: Broker
          name: default
          namespace: slack
    - subscriber:
        ref:
          apiVersion: eventing.knative.dev/v1
          kind: Broker
          name: default
          namespace: mongodb
    - subscriber:
        ref:
          apiVersion: eventing.knative.dev/v1
          kind: Broker
          name: default
          namespace: global-funcs
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: parallel
  namespace: eventing
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Parallel
      name: distribute-to-brokers
