apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: conf-mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef:
        name: root-password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: root-scram
    - name: slack-conf-admin
      db: admin
      passwordSecretRef:
        name: slack-conf-admin-password
      roles:
        - name: dbOwner
          db: slack-conf
      scramCredentialsSecretName: hypsibius-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 50m
                  memory: 100M
                limits:
                  cpu: 500m
                  memory: 300M
            - name: "mongod"
              resources:
                requests:
                  cpu: 100m
                  memory: 500M
                limits:
                  cpu: 2000m
                  memory: 2000M
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: root-password
  namespace: mongodb
type: Opaque
data:
  password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-conf-admin-password
  namespace: mongodb
type: Opaque
data:
  password: SHlwc2liaXVz
