apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: slack-group-left
  namespace: mongodb
spec:
  broker: default
  filter:
    attributes:
      type: group_left
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: slack-channel-management
