apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    name: knative-eventing
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    name: knative-serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: slack
  labels:
    name: slack
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
  labels:
    name: ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: eventing
  labels:
    name: eventing
---
apiVersion: v1
kind: Namespace
metadata:
  name: global-funcs
  labels:
    name: global-funcs
