apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: slack-app-home-opened-rabbit-binding
  namespace: slack
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        function.knative.dev/name: slack-app-home-opened
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: rabbit-broker
      namespace: slack
