apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-cluster
  namespace: rabbit
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  resources:
    requests:
      cpu: 200m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
